[features]
seeds = true

[programs.localnet]
spl_token_faucet = "9XXyjMZtennyC1fRSLvUpiq9UuAfFpCS1a8RSzcg8rMH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
